### ISSUE TITLE
null is not an object (evaluating this._hassProvider.hass.states)

### ISSUE THREAD

**Issue by c4weddell** [francois-le-ko4la/lovelace-entity-progress-card#19]
After upgrading 1.1.0 to 1.1.2 I have started to get **null is not an object (evaluating this._hassProvider.hass.states)** errors showing up on my dashboard (code below).

If I edit the card it displays correctly in the edit screen and if I select save all of the Entity Progress Cards I am using then all display correctly (not just the one I edited).

I have cleared caches, used different browsers but all show the same behaviour.  Any ideas?

```
type: custom:entity-progress-card
entity: sensor.total_solar_production
unit: "%"
name: Total solar
theme: battery
layout: horizontal
bar_size: medium
show_more_info: true
max_value: sensor.total_estimated_energy_production_today
min_value: 0
grid_options:
  columns: 6
  rows: 1
```

Core 2025.3.3
Supervisor 2025.03.2
Operating System 14.2
Frontend 20250306.0
