### ISSUE TITLE
Feature request: badge support

### ISSUE THREAD

**Issue by erikgeurts** [francois-le-ko4la/lovelace-entity-progress-card#26]
I can't say enough how much I enjoy using your card! It fits in very well on my dashboards where I also use the Mushroom cards, and I'm especially fond of the template card for its versatility.

One feature of the template card I like a lot is the ability to display a badge:

![Image](https://github.com/user-attachments/assets/2e980ce5-855e-4cb1-befa-ad8149091396)

In this example, which involves my car charger, I'm displaying a badge that indicates if the charge point is currently set to 1-phase or 3-phase mode.

I'd love to be able to display a badge on this card that shows the current state of charge of my car, to indicate if the car is currently connected to a charger and/or actually charging:

![Image](https://github.com/user-attachments/assets/e9009e3a-38f8-47c1-bcd0-e09f8ad7fde3)

Template support for such a badge would be magnificent, so that I could dynamically change the symbol and the color of the badge.

Is this something you might be willing to consider?

p.s. 'vandaag' means 'aujourd'hui' in Dutch, and 'nu' means 'maintenant', not 'naked' :)

**Comment by francois-le-ko4la** [comment]
hi @erikgeurts,

Good idea.
Now I am on another topic and with a limited bandwith.
I will take a look on it soon.

TY.

**Comment by francois-le-ko4la** [comment]
Hello,

I am working on jinja template. Thats seems to be good and will help on this topic...

![Image](https://github.com/user-attachments/assets/d2eef403-411a-4478-9261-2298c4e588c8)

TY.

**Comment by erikgeurts** [comment]
very nice!!

I created this card:

```
type: custom:entity-progress-card
entity: sensor.piglet_battery
unit: "%"
theme: optimal_when_high
bar_size: large
tap_action:
  action: more-info
watermark:
  type: line
  low: 30
  low_color: white
  disable_high: true
badge: >-
  {% if is_state('binary_sensor.piglet_charging','on') %}
    mdi:battery-charging
  {% endif %}
```

and it displays as follows while the robot mower is charging:

![Image](https://github.com/user-attachments/assets/d4a17d51-6f35-4724-8100-f3aceb84da37)

Just out of curiosity: how is the color of the badge determined? It seems to always come back as green. If that's indeed the case, perhaps a nice tweak might be a templatable badge_color setting?
