### ISSUE TITLE
Watermark: not entirely clear how to set up

### ISSUE THREAD

**Issue by erikgeurts** [francois-le-ko4la/lovelace-entity-progress-card#28]
I'm experimenting with the new watermark feature, I like the idea very much.

My first experiment is to display the voltage of the electricity grid as reported by my smart meter.

The electricity code dictates that the voltage must 230V plus or minus 10%, so anything between 207V and 253V is technically correct.

I created this YAML:

```
type: horizontal-stack
cards:
  - type: custom:entity-progress-card
    entity: sensor.p1_meter_3c39e728d3a6_active_voltage_l1
    min_value: 200
    max_value: 260
    unit: V
    decimal: 0
    tap_action:
      action: more-info
    force_circular_background: true
    icon: mdi:sine-wave
    bar_size: large
    bar_color: green
    watermark:
      high: 253
      high_color: red
      low: 207
      low_color: red
```

However, when I view the card, it turns out like this:

![Image](https://github.com/user-attachments/assets/abb1f44f-33da-48cb-86ca-6a03cbbdd5d5)

Did I misinterpret the documentation?
