### ISSUE TITLE
Adding more action/script examples

### ISSUE THREAD

**Issue by afkdk** [francois-le-ko4la/lovelace-entity-progress-card#29]
Digging into the battery domain, I would like to add a toggle or script action for switching on the switch for the charger of the battery.

I have tried this:

```
icon_tap_action: perform-action
action:
  service: script.toggle_entity
  data:
    entity_id: switch.sovevaerelse_oneplusmclaren_charger_surfou_plug

```

It is likely the concept/context/syntax that is completely wrong but I am new to this part of the HA universe...

BTW., the script for toggle_entity is this:

```
toggle_entity:
  alias: Toggle Entity
  sequence:
    - service: switch.toggle
      target:
        entity_id: "{{ entity_id }}"
```

So I suggest that you maybe could supply an example (code) for either the toggle (syntax) or using an action (script)?

TIA

**Comment by francois-le-ko4la** [comment]
hello afkdk,

100% agree I did not explain everything in my documentation.
In the end, because I use the same mechanism than HA. There is no difference in the syntax.

You can find everything with the editor :
<img width="905" alt="Image" src="https://github.com/user-attachments/assets/ab067d8b-ea2a-40e0-8a7e-84eadf8063bd" />

Or you can use the YAML to do it.

Example, I want to do a toggle on the first entity :
```yaml
hold_action:
  action: toggle
```
I want to toggle a light...
```yaml
hold_action:
  action: perform-action
  perform_action: light.turn_off
  target:
    device_id: 8e866a6134d63ff6144a3a489e874113
```

I want to toggle a switch:
```yaml
hold_action:
  action: perform-action
  perform_action: switch.toggle
  target:
    device_id: 0247b7b6cf27188ee9ab5bbed1dbbac5
```

I covere everything and the possibility are limited only by HA capacity only on this part. That's why the best document is here : https://www.home-assistant.io/dashboards/actions/

Let me know. If my explanation here is clear or not.

In my opinion, you have not only this topic in your mind. We discuss about battery and maybe you want also to control your battery after 80% and switch off automatically. It can be done through HA Automation.

<img width="1194" alt="Image" src="https://github.com/user-attachments/assets/f7520ee2-21fa-4199-b9e2-96e350eead96" />

You will be able to trigger action like :
- if battery > 80%
- switch off ...

Let me know if you need more help.

TY.

**Comment by francois-le-ko4la** [comment]
ha !

In your example your syntax is not correct:
```yaml
icon_tap_action: perform-action
action:
  service: script.toggle_entity
  data:
    entity_id: switch.sovevaerelse_oneplusmclaren_charger_surfou_plug
```

replace it by

```yaml
tap_action:
  action: call-service
  service: script.toggle_entity
  data:
    entity_id: switch.sovevaerelse_oneplusmclaren_charger_surfou_plug
```
