### ISSUE TITLE
Watermark: high marker (line) appears even when not defined

### ISSUE THREAD

**Issue by erikgeurts** [francois-le-ko4la/lovelace-entity-progress-card#31]
I've created a card for the battery in my robot mower (cutely named Piglet), as follows:

```
type: custom:entity-progress-card
entity: sensor.piglet_battery
unit: "%"
theme: optimal_when_high
bar_size: large
tap_action:
  action: more-info
watermark:
  type: line
  low: 30
  low_color: blue
```

However, a line appears for the high boundary as well:

![Image](https://github.com/user-attachments/assets/3089b57a-0913-4b49-aa37-b0d2fcaa1c21)

For this particular use case, my interest is to show the 30% low boundary which is when the robot should return to the dock to recharge. When it does so, it will always recharge to 100%, I have no control over that nor any reason to want to change that, it's the normal operation for this robot mower.
