### ISSUE TITLE
Feature request: Support `timer` and `flextimer` for duration device class

### ISSUE THREAD

**Issue by mill1000** [francois-le-ko4la/lovelace-entity-progress-card#33]
Hi,

Recently tried to use this card for my sprinkler dashboard to display the progress of a water cycle.

Overall it's working well, but I would like to use the `timer` or `flextimer` option for units to display the time remaining in hh:mm:ss format like in #14.

Unfortunately it seems like these options are only explicitly supported for actual timers.

![Image](https://github.com/user-attachments/assets/2ec575e8-0f34-46ad-a38e-86a544bfb997)

```yaml
type: custom:entity-progress-card
entity: sensor.sprinklers_esp8266_cycle_time_remaining
max_value: sensor.sprinklers_esp8266_configured_cycle_time
name: Cycle Time
unit: flextimer
```

The entities in this case all have `device_class: duration`.
![Image](https://github.com/user-attachments/assets/b3bbdbed-540e-447e-92a7-a3828f6cc032)

Bonus points if I could use a separate entity to determine paused/active state. :)
