### ISSUE TITLE
Odd color behavior

### ISSUE THREAD

**Issue by afkdk** [francois-le-ko4la/lovelace-entity-progress-card#35]
Not critical but odd color appearance 😉

I am really glad for my new "battery check board" that both shows charge levels and enables charger activation on the icon!
But somehow there seems to be a glitch - likely in my setup - as the WHITE font and NO progress bar appear at the 20% (and I have also seen it at 35%) - but not at the higher levels...   Both 20% and 35% are interval end points but this is also how it is set up in the examples.

![Image](https://github.com/user-attachments/assets/4bc93d64-4a39-4861-84e3-f45d59f6003a)

```
type: custom:entity-progress-card
show_more_info: true
entity: sensor.ipadpro6_battery_level
unit: "%"
name: iPadPro6
theme: battery
icon_tap_action:
  action: call-service
  service: script.toggle_entity
  data:
    entity_id: switch.sovevarelse_ipadpro6_plug_nous_a1_wifi_socket_1
opacity: 0.8
custom_theme:
  - min: 0
    max: 20
    color: red
  - min: 20
    max: 35
    color: amber
  - min: 35
    max: 50
    color: yellow
  - min: 50
    max: 80
    color: green
  - min: 80
    max: 100
    color: lightgreen
watermark:
  high: 80
  high_color: red
  low: 20
  low_color: grey

```

_PS: The Opacity is in there but I see no difference in my experiments - that may be the culprit?_
