### ISSUE TITLE
Attribute from custom sensor not working as max_value_attribute

### ISSUE THREAD

**Issue by jesperklippel** [francois-le-ko4la/lovelace-entity-progress-card#38]
Hello, 

Love your progress card, but I've been trying to get a sensor attribute as max_value_attribute working.

This is a screenshot of my sensor and its attributes:
![Image](https://github.com/user-attachments/assets/fb707271-60f7-4407-a874-363bece47994)

The important attribute is "watering_interval".

I try to use it in the progress card as follows:

```
type: custom:entity-progress-card
entity: sensor.avocado
max_value_attribute: watering_interval
min_value: 0
```

Attributes are also not showing up in the UI.

Sensor is defined as followed in a yaml file:

```
- sensor:    
    - name: "Avocado"
      unique_id: 7604a08d-1f22-49b8-98e2-e0c9b35a2308
      unit_of_measurement: "Days"
      icon: mdi:sprout
      state: > 
        {% set dt = states('input_datetime.avocado') | as_datetime | as_local %}
        {{ (dt.date() - now().date()).days | abs }}
      attributes:
        plant_name: "Persea Americana"
        watering_interval: 7
        datetime_id: "input_datetime.avocado"
```
