### ISSUE TITLE
Icon Tap, Icon Double Tap and Card Double Tap Broken since 1.3.8, working in 1.3.7

### ISSUE THREAD

**Issue by Duncan1106** [francois-le-ko4la/lovelace-entity-progress-card#40]
I hate to do this again, but i think it is broken again. 
No matter what i assign to the
- icon hold
- icon double
- normal double tap 

action, it always opens more-info

normal hold action is working, if that helps to narrow it down

I'm happy to help with logs, but i didnt find anything broken in browser dev console.

I'm on version 1.3.9, in 1.3.7 it is working alright.
also broken in 1.3.8

I've cleared browser and homeassistant app cache multiple times to make sure it is not my side thats acting up.

heres the code i've used to test it

```
type: custom:entity-progress-card
double_tap_action:
  action: toggle
entity: switch.switch_xyz
icon_double_tap_action:
  action: toggle
tap_action:
  action: none
hold_action:
  action: toggle
icon_tap_action:
  action: none
icon_hold_action:
  action: toggle
```

**Comment by francois-le-ko4la** [comment]
hello @Duncan1106,

My bad.... I tried to optimized this part and I have a side effect.
That should be quick to fix it.

Thank you for your patience and the time you took to share your feedback.

**Comment by francois-le-ko4la** [comment]
hello @Duncan1106,

I released the fix. If you see another issue let me know.

TY.

**Comment by francois-le-ko4la** [comment]
hello @Duncan1106,

Just checking — Can you let me know if all's good?

TY.

**Comment by Duncan1106** [comment]
Seems to function mostly fine.

Just something odd I think, when using a timer, icon double tap seems to start the timer when 'nothing' is selected as action in the UI editor.

Is this intended?

When using something like more-info that fires the correct action.

**Comment by francois-le-ko4la** [comment]
can you share your YAML ?
I will test it asap.

**Comment by francois-le-ko4la** [comment]
When I use this config, all seems to be perfect:
- I get the more-info with double click on card
- same for icon (failback to card definition)

```yaml
type: custom:entity-progress-card-dev
entity: timer.testtimer
tap_action:
  action: none
hold_action:
  action: none
double_tap_action:
  action: more-info
icon_tap_action:
  action: none
icon_hold_action:
  action: none
icon_double_tap_action:
  action: none
```

**Comment by francois-le-ko4la** [comment]
ha!
Yes, that's the default behavior. When you double-tap on an icon with `action: none`, the fallback action triggers on the card itself, since the icon is part of the card.
I checked again with the "tile" card, and it behaves the same way.

Note that `action: interact` is not a standard action in Home Assistant.

but but but......
We can do something like that :

- create a script to start/pause the timer :
```yaml
sequence:
  - choose:
      - conditions:
          - condition: state
            entity_id: timer.testtimer
            state: active
        sequence:
          - action: timer.pause
            target:
              entity_id: timer.testtimer
            data: {}
      - conditions:
          - condition: state
            entity_id: timer.testtimer
            state: paused
        sequence:
          - action: timer.start
            metadata: {}
            data: {}
            target:
              entity_id: timer.testtimer
      - conditions:
          - condition: state
            entity_id: timer.testtimer
            state: idle
        sequence:
          - action: timer.start
            metadata: {}
            data: {}
            target:
              entity_id: timer.testtimer
alias: TestTimer
description: ""
```

- define it:
```yaml
...
double_tap_action:
  action: call-service
  service: script.testtimer_2
```

Change the names according to your need and test it. That should be nice.
