### ISSUE TITLE
[Bug]: Secondary info displays Div0

### ISSUE THREAD

**Issue by pterisaur** [francois-le-ko4la/lovelace-entity-progress-card#41]
### Requirements

- [x] I checked the README.
- [x] I have updated entity-progress-card to the latest available version.
- [x] I did a search to see if there is a similar issue.

### Current Behavior

I'm using auto-entities to generate a list of progress cards. This used to work perfectly, but as of a recent update all the cards now display 'Div0' as secondary info and no progress on any of the bars.

-----

My use case:

The entities I'm loading contain the number of days remaining before a task is due, like a countdown. In the cards, I am displaying progress only if there's 1 week or less remaining — min: 7 days remaining, max: 0 days remaining (today).

### Expected Behavior

If `sensor.task_remaining_water_landscaping` has a current value of 1, the progress bar should be filled 86% (6 of 7 days filled). 

### Context

Here's an example card yaml. 

```yaml
type: custom:entity-progress-card
force_circular_background: true
entity: sensor.task_remaining_water_landscaping
unit: " days remaining"
min_value: 7
max_value: 0
decimal: 0
name: Water Landscaping
icon: mdi:leaf
layout: horizontal
color: green
bar_color: green
fill_container: true
```

And here's what I see as a result:
<img width="459" alt="Image" src="https://github.com/user-attachments/assets/d0c03736-ac90-42a0-a71c-c78259848915" />

### Environment

```markdown
- Browser: Safari 18.5
- HA Version: 2025.5.2
- Entity Progress Card: 1.3.11
```
