### ISSUE TITLE
[Feature]: Add entity_row option - frameless

### ISSUE THREAD

**Issue by davidlb** [francois-le-ko4la/lovelace-entity-progress-card#45]
### Requirements

- [x] I checked the README.
- [x] I have updated entity-progress-card to the latest available version.
- [x] I did a search to see if there is a similar issue.

### Is your feature request related to a problem?

Hi, 
I've just switched from bar-card to your card, I really love it. I just miss the entity_row option as in bar-card. 

### Describe the solution you'd like

In fact, your card is so much configurable, it would be nice to not have to install to mod-card just for removing border.

![Image](https://github.com/user-attachments/assets/52648a04-ebb3-4cf6-b280-78bc6a332c2b)

### Additional context

Thanks for your good work!
David

**Comment by francois-le-ko4la** [comment]
Hello @davidlb, 

Thank you for your feedback and your request !
If I understand correctly : border & background at the same time.
That should be easy to implement.

TY.

**Comment by francois-le-ko4la** [comment]
draft:

<img width="1003" alt="Image" src="https://github.com/user-attachments/assets/fe9bf4e4-d358-4713-8b06-3066e4b80f03" />

frameless: true/false

**Comment by francois-le-ko4la** [comment]
hello @davidlb,

Done. Next release btwn tonight and tomorrow.

TY.

**Comment by francois-le-ko4la** [comment]
Hello @davidlb 

I released the new version here: https://github.com/francois-le-ko4la/lovelace-entity-progress-card/releases/tag/1.4.2
Please let me know if this release meets all your needs.

TY.

**Comment by davidlb** [comment]
Hi @francois-le-ko4la , thanks for this new release, it's much better better. I tried to do changes in the code to improve your component but I didn't succeed, not enough skills...

Depending on the theme, there is a box-shadow applied to the card and it should be overwritten:

![Image](https://github.com/user-attachments/assets/dc2e7268-2a70-40c3-9627-ebffeacd5a11)


```
.${CARD.style.dynamic.frameless.class} {
    border: 0;
    background-color: transparent;
    box-shadow: none;
  }
```

There is also a hover declaration (in the clickableCard CSS class), I think it could be removed in frameless mode to be consistent with other rows.

![Image](https://github.com/user-attachments/assets/7170e84d-73c7-44e9-b730-a07e34e5e094)

To be picky and consistent with other rows, in frameless mode : 
* container should not have margin on both side
* the icon area is 40px x 40px on all other rows and it's 36px x 36px on your card
* title should be not in bold but normal
* secondary info should use the secondary-info var instead of primary

It would give this rendering

![Image](https://github.com/user-attachments/assets/54f309b5-bde6-4d79-8c34-4450f4284e8d)

I really appreciate all your work on this really good card and I would understand if you are not able to fullfill my requests.
David

**Comment by jam3sward** [comment]
Thanks for this update, it works really nicely!
![Image](https://github.com/user-attachments/assets/f9ca4a3c-ec0c-4ad5-8fac-23b65e2cd484)

**Comment by davidlb** [comment]
Hi @francois-le-ko4la ,
Here is my yaml for the card:
```
type: entities
entities:
  - entity: sensor.temperature_exterieur
    name: Température
    secondary_info: last-changed
  - entity: sensor.temp_mini_24_heures
    name: Température mini (24h)
    icon: mdi:thermometer-low
    secondary_info: last-changed
  - name: Qualité de l'air
    type: custom:entity-progress-card
    entity: sensor.qualite_globale_saint_chamond
    min_value: 0
    max_value: 7
    custom_info: "{{ state_attr('sensor.qualite_globale_saint_chamond', 'Libellé') }}"
    disable_unit: true
    bar_size: large
    frameless: true
```
