### ISSUE TITLE
[Bug]: Watermark: opacity

### ISSUE THREAD

**Issue by WaterInTheLake** [francois-le-ko4la/lovelace-entity-progress-card#57]
### Requirements

- [x] I checked the README.
- [x] I have updated entity-progress-card to the latest available version.
- [x] I did a search to see if there is a similar issue.

### Current Behavior

While using the watermark feature, and when the opacity is set to 1 (should be fully opaque), the color still appears to have some degree of transparency.

![Image](https://github.com/user-attachments/assets/be110c9c-b4bd-4839-aca0-f6a31fea12ba)

### Expected Behavior

I would expect it to be more like this, where the high and low marker have the same (opaque) color as long as opacity is set to 1. And that the default value should be around 0.8, but if you override it to 1.0, then the transparency should disappear completely.

![Image](https://github.com/user-attachments/assets/33c73f1c-7456-4f1f-9f8e-e2fcb6c5212d)

### Steps To Reproduce

See YAML-config below.

### Context

YAML state
```yaml
type: custom:entity-progress-card
entity: sensor.floor_heating_temperature
name: Floor Heating Temperature
decimal: 0
max_value: 22
theme: temperature
min_value: 12
bar_size: medium
hide:
  - icon
custom_theme:
  - min: 0
    max: 16
    color: blue
  - min: 16
    max: 19
    color: white
  - min: 19
    max: 50
    color: red
watermark:
  high: 20
  high_color: red
  low: 16
  low_color: red
  type: bar
  opacity: 1
```

### Environment

```markdown
- Browser: Chrome 136.0.7103.114
- HA Version: 2025.5.3
- Entity Progress Card: 1.4.6
```

### Anything else?

Slightly related to https://github.com/francois-le-ko4la/lovelace-entity-progress-card/issues/28

Also, I'd like to thank you for your dedicated work with all of this!👍
