### ISSUE TITLE
[Bug]: custom_theme not working right?

### ISSUE THREAD

**Issue by Krojack** [francois-le-ko4la/lovelace-entity-progress-card#59]
### Requirements

- [x] I checked the README.
- [x] I have updated entity-progress-card to the latest available version.
- [x] I did a search to see if there is a similar issue.

### Current Behavior

Not sure if I'm doing something wrong or this is a bug.
None of the custom_theme values seem to work. No matter what values I set the icon & bar colors are just grey. I've used other themes just fine such as `theme: humidity` and `theme: temperature`.

### Context

YAML state
```yaml
type: custom:entity-progress-card
entity: sensor.ping_vpn
unit: ms
decimal: 0
min_value: 45
max_value: 150
bar_size: medium
custom_theme:
  - min: 0
    max: 65
    color: green
  - min: 65
    max: 85
    color: deep-orange
  - min: 80
    max: 500
    color: red
```

### Environment

```markdown
- Browser: FF 139.0.1
- HA Version: 2025.05.3
- Entity Progress Card: 1.4.6
```
