### ISSUE TITLE
[Bug]: hiding the name hides the bar

### ISSUE THREAD

**Issue by dougyip** [francois-le-ko4la/lovelace-entity-progress-card#63]
### Requirements

- [x] I checked the README.
- [x] I have updated entity-progress-card to the latest available version.
- [x] I did a search to see if there is a similar issue.

### Current Behavior

Hiding the name or having too short of a name makes the bar invisible or tiny
hide:
  - name

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Entity Progress Card:
```

**Comment by janchrillesen** [comment]
I have noticed the same behavior, but only under certain conditions. Using the card standalone, it works fine - but then it's part of a picture element card, I see the reported behavior (I am trying to use your card to replace the now defunct bar-card)

```
type: custom:entity-progress-card
entity: sensor.stormtrooper_battery_level_2
decimal: 0
bar_size: large
theme: optimal_when_high
frameless: true
hide:
  - icon
  - name
  - secondary_info
style:
  top: 85%
  left: 53%
  font-size: 100%
  font-weight: normal
  color: rgb(0,0,0)
```
