### ISSUE TITLE
[Bug]: disable_unit: true messing up custom theme

### ISSUE THREAD

**Issue by nicknol** [francois-le-ko4la/lovelace-entity-progress-card#68]
### Requirements

- [x] I checked the README.
- [x] I have updated entity-progress-card to the latest available version.
- [x] I did a search to see if there is a similar issue.

### Current Behavior

If `disable_unit: true` then always the last option of the custom_theme is used to colorize the bar and icon.

with a `sensor.wetter_3e_uv_index` having value of 5 we would expect to see the bar and icon in red, but it's shown in purple.
```
type: custom:entity-progress-card
entity: sensor.wetter_3e_uv_index
name: aktuell
decimal: 0
min_value: 0
max_value: 11
disable_unit: true
icon: mdi:sun-wireless
custom_theme:
  - min: 0
    max: 2
    color: green
  - min: 2
    max: 4
    color: amber
  - min: 4
    max: 6
    color: red
  - min: 6
    max: 8
    color: darkred
  - min: 8
    max: 11
    color: purple
```
![Image](https://github.com/user-attachments/assets/bef176cb-629b-4dcc-83d7-e5c7ef5c2959)

with `disable_unit: false` the icon and bar are colored correctly in red

with a `sensor.wetter_3e_uv_index` having value of 5 we would expect to see the bar and icon in red, but it's shown in purple.
```
type: custom:entity-progress-card
entity: sensor.wetter_3e_uv_index
name: aktuell
decimal: 0
min_value: 0
max_value: 11
disable_unit: false
icon: mdi:sun-wireless
custom_theme:
  - min: 0
    max: 2
    color: green
  - min: 2
    max: 4
    color: amber
  - min: 4
    max: 6
    color: red
  - min: 6
    max: 8
    color: darkred
  - min: 8
    max: 11
    color: purple
```
![Image](https://github.com/user-attachments/assets/c40d74b3-7834-456d-a485-60ee1dd059fe)

reducing the amount of options proves it:

![Image](https://github.com/user-attachments/assets/83d19d5e-a666-4016-8ea6-af887d35b87f)

### Expected Behavior

`disable_unit: true` should not impact the selected option in the `custom_theme`

### Steps To Reproduce

see above

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: edge and firefox
- HA Version: 2025.5.3
- Entity Progress Card: 1.4.8
```

### Anything else?

When the sensor has the configured minimum value, 0 in the example, the option of the custom_theme is chosen, in the example bar and icon are green.

![Image](https://github.com/user-attachments/assets/7ebdecb9-d7f6-4e05-9425-548c3ca30802)
